repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff  # linter
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format  # formatter
        types_or: [ python, pyi, jupyter ]




