name: Ruff
on: [ push, pull_request ]
jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set Python Version
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Python Ruff Lint and Format
      uses: adityabhangle658/ruff-python-lint-format-check-pr@v1.0.3



